version: "3.9"
services:
  web:
    build: ./server
    command: python3 -m flask run --host=0.0.0.0
    ports:
      - "5000:5000"
  client:
    build: ./client
    volumes:
      - "./client/:/app"
      - "/app/node_modules"
    ports:
      - "3001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
